// Generated by CoffeeScript 1.12.7
(function() {
  var greeting;

  module.exports.greeting = greeting = function(name) {
    return "Hello " + name + "!";
  };

  console.log(greeting("World"));

}).call(this);

//# sourceMappingURL=index.js.map
